name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'maven'

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Rename JAR
      run: |
        ORIGINAL_JAR=$(ls target/*.jar | grep -v 'original' | head -n 1)
        echo "Renaming $ORIGINAL_JAR to target/spring-boot-app.jar"
        mv "$ORIGINAL_JAR" target/spring-boot-app.jar

    - name: Upload JAR artifact
      uses: actions/upload-artifact@v4
      with:
        name: spring-boot-app
        path: target/spring-boot-app.jar

  deploy:
    needs: build
    runs-on: ubuntu-latest
    
    env:
      GCP_PROJECT_ID: unique-spirit-469000-h2
      GCP_INSTANCE_NAME: instance-springboot-app-41082025-0718
      GCP_ZONE: us-central1-c
      
    steps:
    - name: Download JAR artifact
      uses: actions/download-artifact@v4
      with:
        name: spring-boot-app
    
    - name: Authenticate to GCP
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}
    
    - name: Ensure target folder exists on VM
      run: |
        echo "Ensuring /var/www/app/ exists on remote VM..."
        gcloud compute ssh ${{ env.GCP_INSTANCE_NAME }} \
        --project=${{ env.GCP_PROJECT_ID }} \
        --zone=${{ env.GCP_ZONE }} \
        --command="sudo mkdir -p /var/www/app && sudo chown \$USER /var/www/app" \
        --quiet
    
    - name: Deploy to GCP
      run: |
        echo "Starting deployment to GCP..."
        
        gcloud compute scp spring-boot-app.jar \
        ${{ env.GCP_INSTANCE_NAME }}:/var/www/app/ \
        --project=${{ env.GCP_PROJECT_ID }} \
        --zone=${{ env.GCP_ZONE }} \
        --quiet
        
        echo "JAR file transferred successfully. Restarting service..."

        gcloud compute ssh ${{ env.GCP_INSTANCE_NAME }} \
        --project=${{ env.GCP_PROJECT_ID }} \
        --zone=${{ env.GCP_ZONE }} \
        --command="sudo systemctl stop springboot-app.service || true; sudo systemctl start springboot-app.service" \
        --quiet
        
        echo "Deployment complete."